var rideInfo = [
    {dest1:"Mirpur", dest2:"Dhanmondi", fare:"10", by:"Car", person:"4"},
    {dest1:"Kakrail", dest2:"Uttara", fare:"12", by:"Car", person:"4"},
    {dest1:"Motijheel", dest2:"Mirpur", fare:"13", by:"Car", person:"4"},
    {dest1:"Farmgate", dest2:"Jatrabari", fare:"11", by:"Car", person:"4"},
    {dest1:"Farmgate", dest2:"Shahbag", fare:"15", by:"Car", person:"4"},
    {dest1:"Shahbag", dest2:"Mohakhali", fare:"20", by:"Car", person:"4"},
    {dest1:"Malibag", dest2:"Badda", fare:"9", by:"Car", person:"4"},
    {dest1:"Rampura", dest2:"Kawran Bazar", fare:"17", by:"Car", person:"4"},
    {dest1:"Nilkhet", dest2:"Dhanmondi", fare:"20", by:"Car", person:"4"},
    {dest1:"Wari", dest2:"Rampura", fare:"18", by:"Car", person:"4"},

    {dest1:"Mirpur", dest2:"Dhanmondi", fare:"4", by:"Bus", person:"1"},
    {dest1:"Kakrail", dest2:"Uttara", fare:"3", by:"Bus", person:"1"},
    {dest1:"Motijheel", dest2:"Mirpur", fare:"2", by:"Bus", person:"1"},
    {dest1:"Farmgate", dest2:"Jatrabari", fare:"3", by:"Bus", person:"1"},
    {dest1:"Farmgate", dest2:"Shahbag", fare:"6", by:"Bus", person:"1"},
    {dest1:"Shahbag", dest2:"Mohakhali", fare:"4", by:"Bus", person:"1"},
    {dest1:"Malibag", dest2:"Badda", fare:"5", by:"Bus", person:"1"},
    {dest1:"Rampura", dest2:"Kawran Bazar", fare:"7", by:"Bus", person:"1"},
    {dest1:"Nilkhet", dest2:"Dhanmondi", fare:"3", by:"Bus", person:"1"},
    {dest1:"Wari", dest2:"Rampura", fare:"4", by:"Bus", person:"1"},

    {dest1:"Mirpur", dest2:"Dhanmondi", fare:"11", by:"Bike", person:"1"},
    {dest1:"Kakrail", dest2:"Uttara", fare:"4", by:"Bike", person:"1"},
    {dest1:"Motijheel", dest2:"Mirpur", fare:"3", by:"Bike", person:"1"},
    {dest1:"Farmgate", dest2:"Jatrabari", fare:"2", by:"Bike", person:"1"},
    {dest1:"Farmgate", dest2:"Shahbag", fare:"6", by:"Bike", person:"1"},
    {dest1:"Shahbag", dest2:"Mohakhali", fare:"9", by:"Bike", person:"1"},
    {dest1:"Malibag", dest2:"Badda", fare:"4", by:"Bike", person:"1"},
    {dest1:"Rampura", dest2:"Kawran Bazar", fare:"5", by:"Bike", person:"1"},
    {dest1:"Nilkhet", dest2:"Dhanmondi", fare:"6", by:"Bike", person:"1"},
    {dest1:"Wari", dest2:"Rampura", fare:"7", by:"Bike", person:"1"},

    {dest1:"Mirpur", dest2:"Dhanmondi", fare:"3", by:"Train", person:"1"},
    {dest1:"Kakrail", dest2:"Uttara", fare:"4", by:"Train", person:"1"},
    {dest1:"Motijheel", dest2:"Mirpur", fare:"9", by:"Train", person:"1"},
    {dest1:"Farmgate", dest2:"Jatrabari", fare:"10", by:"Train", person:"1"},
    {dest1:"Farmgate", dest2:"Shahbag", fare:"12", by:"Train", person:"1"},
    {dest1:"Shahbag", dest2:"Mohakhali", fare:"7", by:"Train", person:"1"},
    {dest1:"Malibag", dest2:"Badda", fare:"6", by:"Train", person:"1"},
    {dest1:"Rampura", dest2:"Kawran Bazar", fare:"5", by:"Train", person:"1"},
    {dest1:"Nilkhet", dest2:"Dhanmondi", fare:"7", by:"Train", person:"1"},
    {dest1:"Wari", dest2:"Rampura", fare:"8", by:"Train", person:"1"}

]
export default rideInfo;